# Generated by Django 2.2.2 on 2019-06-10 17:46

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='friday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='monday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='saturday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='thursday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tuesday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ManyToManyField(to='attendance.Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='wednesday',
            field=models.CharField(choices=[('Present', 'P'), ('Absent', 'A'), ('NA', 'NA')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.BigIntegerField(default=attendance.models.get_year),
        ),
    ]
