# Generated by Django 2.2.2 on 2019-06-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_samplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
    ]
