# Generated by Django 2.2.2 on 2019-06-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190612_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
