# Generated by Django 2.2.2 on 2019-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20190617_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.CharField(default=6, max_length=100),
        ),
    ]
