# Generated by Django 2.2.2 on 2019-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20190617_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ManyToManyField(to='attendance.Student'),
        ),
    ]
